// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhG5ijNNvFDBPzFjRcmSMpAwB3BMLrK_c',
    appId: '1:333872222121:web:4383e3112f8d549ee37eb8',
    messagingSenderId: '333872222121',
    projectId: 'chat-app-95b8b',
    authDomain: 'chat-app-95b8b.firebaseapp.com',
    storageBucket: 'chat-app-95b8b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1FqR5sGh4nAbCPTnZ79qmm2Vluw4Beg0',
    appId: '1:333872222121:android:416da8ae4713bd9be37eb8',
    messagingSenderId: '333872222121',
    projectId: 'chat-app-95b8b',
    storageBucket: 'chat-app-95b8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDR-SE44u1cE-Np4PYy99TGwyZ6bn7CTOk',
    appId: '1:333872222121:ios:e763801387d619b1e37eb8',
    messagingSenderId: '333872222121',
    projectId: 'chat-app-95b8b',
    storageBucket: 'chat-app-95b8b.appspot.com',
    iosClientId: '333872222121-hoftlfvm1htnojesk9c7a4b54rbi5m33.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDR-SE44u1cE-Np4PYy99TGwyZ6bn7CTOk',
    appId: '1:333872222121:ios:3db851f7186ce077e37eb8',
    messagingSenderId: '333872222121',
    projectId: 'chat-app-95b8b',
    storageBucket: 'chat-app-95b8b.appspot.com',
    iosClientId: '333872222121-7jvhk2kr4fct6hc8qh8aj8u752j1n1eq.apps.googleusercontent.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
